---
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
  notify: Restart MySQL

- name: "Install ansible python3 mysql dependency"
  apt:
    name: python3-mysqldb
    state: latest
  notify: Restart MySQL